zkouska/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.templatetags import rest_framework

import api
from api.views import *
from accounts.views import *
from viewer.models import *
from viewer.views import *
from zkouska import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello', hello),
    path('hello2/<s>', hello2),
    path('hello3/', hello3),
    path('hello4/', hello4),

    path('', index, name='index'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),     # defaultní views pro přihlašování/odhlašován/...

    path('accounts/profile_create/<pk>', ProfileCreateView.as_view(), name='profile_create'),
    path('accounts/profile/<pk>/', profile, name='profile'),
    path('accounts/profile_edit/', profile_edit, name='profile_edit'),


    path('News/', news, name='News'),
    path('NewsOnDVD', newsOnDVD, name='NewsOnDVD'),
    path('movies/', MoviesListView.as_view(), name='movies2'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('administration/', administration, name='administration'),
    path('country_admin/', CountryView.as_view(), name='country_admin'),
    path('movies_admin/', MoviesView.as_view(), name='movies_admin'),
    # path('movies/', MoviesTemplateView.as_view(), name=MoviesTemplateView),
    # path('movies2/', MoviesListView.as_view(), name=MoviesListView),
    path('movie/<pk>/', movie, name='movie'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('actors/', actors, name='actors'),
    path('actor/<pk>/', actor, name='actor'),
    #path('person/create/', PersonCreateView.as_view(), name='person_create'),
    path('genre_admin/', GenresView.as_view(), name='genre_admin'),
    path('genre/<pk>/', movies_by_genre, name='genre'),
    path('genre/update/<pk>', GenreUpdateView.as_view(), name='genre_update'),
    path('genres/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),
    path('country/<pk>/', movies_by_country, name='country'),
    # path('administration/', CountryView.as_view(), name='country_view'),
    path('countries/create/', CountryCreateView.as_view(), name='create_country'),
    path('countries/delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),
    path('countries/update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('persons_admin/', PersonsView.as_view(), name='persons_admin'),
    path('person/create/', PersonCreateView.as_view(), name='person_create'),
    #path('person/create/', PersonModelForm, name='person_create'),
    path('actor/update/<pk>/', PersonUpdateView.as_view(), name='person_update'),
    path('person/delete/<pk>/', PersonDeleteView.as_view(), name='person_delete'),
    path('person/<pk>/', person, name='person'),

    path('rate_movie/', rate_movie, name='rate_movie'),
    path('add_comment/', add_comment, name='add_comment'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/movies/', api.views.Movies.as_view()),

    path('api/movie/<pk>/', api.views.MovieDetail.as_view()),

    path('api/person/<pk>/', api.views.PersonDetail.as_view()),
    path('api/persons/', api.views.PersonsList.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from datetime import date, datetime

from django.db import models
from django.db.models import Model, CharField, IntegerField, TextField, DateField, ForeignKey, DO_NOTHING, \
    ManyToManyField, SET_NULL, DateTimeField, ImageField
from django.contrib.auth.models import User


# Create your models here.


class Country(Model):
    name = CharField(max_length=64, null=False, blank=False, unique=True)

    class Meta:
        verbose_name_plural = "Countries"

    def __str__(self):
        return f"{self.name}"


class Genre(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)  # CharField => VARCHAR

    def __str__(self):
        return f"{self.name}"


class Person(Model):
    first_name = CharField(max_length=32, null=False, blank=False)
    last_name = CharField(max_length=32, null=False, blank=False)
    nationality = CharField(max_length=64, null=True, blank=True)
    birth_date = DateField(null=True, blank=True)
    date_of_death = DateField(null=True, blank=True)
    biography = TextField(null=True, blank=True)
    person_image = ImageField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def calculate_age(self):
        today = datetime.now().date()

        if self.date_of_death:
            age_at_death = (self.date_of_death - self.birth_date).days // 365
            return age_at_death
        else:
            age_now = (today - self.birth_date).days // 365
            return age_now

    def get_image(self):
        return Image.objects.filter(person=self)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        ordering = ['last_name', 'first_name']


class Movie(Model):
    title_orig = CharField(max_length=64, null=False, blank=False)
    title_cz = CharField(max_length=64, null=True, blank=True)
    title_sk = CharField(max_length=64, null=True, blank=True)
    countries = ManyToManyField(Country, blank=True, related_name='movies_in_country')  # umožňuje jít oběma směry tabulek
    genres = ManyToManyField(Genre, blank=True, related_name='movies_of_genre')
    directors = ManyToManyField(Person, blank=False, related_name='directing_movie')
    actors = ManyToManyField(Person, blank=True, related_name='acting_in_movie')
    year = IntegerField(null=True, blank=True)
    video = CharField(max_length=128, null=True, blank=True)
    description = TextField(null=True, blank=True)
    movie_image = ImageField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def __str__(self):
        if self.title_cz:
            title_name = self.title_cz
        elif self.title_sk:
            title_name = self.title_sk
        else:
            title_name = self.title_orig

        if self.year is not None:
            title_name += f" ({self.year})"

        return title_name

    def get_image(self):
        return Image.objects.filter(movie=self)

    class Meta:
        ordering = ['title_orig']


class Rating(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    user = ForeignKey(User, null=True, on_delete=SET_NULL)
    rating = IntegerField(null=False, blank=False)

    def __str__(self):
        return f"{self.movie}: {self.rating} by {self.user}"


class Comment(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    user = ForeignKey(User, null=True, on_delete=SET_NULL)
    comment = TextField(null=False, blank=False)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.movie}: {self.user} {self.comment[:20]}"


class Image(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False, default=None)
    person_image = ForeignKey(Person, on_delete=DO_NOTHING, null=False, blank=False, default=None)
    # url = CharField(max_length=128, null=False, blank=False)
    image = ImageField(upload_to='images/', default=None, null=False, blank=False)  #, height_field=None, width_field=None, max_length=500)
    description = TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.movie}: {self.description[:50]}"

viewer/templates/News.html
{% extends "base.html" %}

{% block content %}
        <h2>News in Cinemas.<span id="date-time"></span></h2>
        <h2>In Cinemas from 12.28.2023</h2>
        <h3>Jedeme na teambuilding</h3>
        <img class="News" src="./pic of movie/Jedeme na teambuilding.jpg" alt="Jedeme na teambuilding">
        <p>Komedie</p>
        <p>Česko / Slovensko, 2023, 105 min</p>
        <p>Když si myslíte, že máte ve všech směrech skvěle našlápnuto a nic vás nezastaví, tak se většinou hodně pletete. Ambiciózní korporátní zaměstnanec Aleš (Jakub Prachař) je svým narcistickým šéfem (Alexander Bárta) místo povýšení přeložen do nejhoršího firemního oddělení - do call centra. Tam velice rychle musí přijít na to, jak spolu s potrhlou konspirátorkou Marcelou (Petra Polnišová), neurotickým nihilistou Michalem (Vojta Kotek), vzorňačkou Jitkou (Anna Polívková) a dalšími bizarními kolegy vytvořit sehranou partu. Jen tak může během teambuildingového víkendu porazit bývalé kolegy, zachránit své nové oddělení před zrušením a hlavně najít ztracenou sebeúctu. (CinemArt)</p>
        <p></p>
        <h3>Méďovy vánoce</h3>
        <img class="News" src="./pic of movie/medovy vanoce.jpg" alt="Méďovy vánoce">
        <p>Rodinný</p>
        <p>Norsko, 2022, 80 min</p>
        <p>Sněhové vločky, vůně Vánoc a třpytivá světýlka zaplaví vánoční městečko, kam se vypraví malá Mariann, aby tam objevila neuvěřitelné tajemství: plyšový medvídek na poličce stánku právě pohnul hlavou! Mariann hned padl do oka, a tak si pod stromeček nepřeje nic jiného, než toto živé plyšové zvířátko. Méďa má však jiné plány, sní totiž o bohatém majiteli, který ho bude rozmazlovat. Když však Méďu odvedou do staré dřevárny, jeho nový nejlepší přítel, ježek Žužu, mu pomůže uvědomit si, na čem v životě opravdu záleží. (Forum Film CZ)</p>
        <p></p>
        <h3>Pokoj zázraků</h3>
        <img class="News" src="./pic of movie/Pokoj zázraků.png" alt="Pokoj zázraků">
        <p>Drama</p>
        <p>Francie, 2023, 94 min</p>
        <p>Thelmin pečlivě naplánovaný život nabírá na obrátkách ve chvíli, kdy se její dvanáctiletý syn Louis ocitá po dopravní nehodě v kómatu. Thelma je odhodlaná přivést ho zpátky do života stůj co stůj. Aby mu ukázala, co všechno krásného na něj v životě ještě čeká, rozhodne se za něj „v zastoupení“ uskutečnit jeho sny, tedy „10 věcí, které je třeba udělat před koncem světa“, jak si to Louis poznamenal do deníku. Cesta za splněním snů dospívajícího chlapce ji ovšem dovede dál, než si vůbec dokázala představit… a nakonec způsobí, že se i jí znovu začne líbit na světě. (Bohemia MP)</p>
        <p></p>
        <h2>In Cinemas from 12.21.2023</h2>
        <h3>Aquaman a ztracené království</h3>
        <img class="News" src="./pic of movie/Aquaman a ztracené království.jpg" alt="Aquaman a ztracené království">
        <p>Akční, Dobrodružný, Fantasy</p>
        <p>USA, 2023, 124 min</p>
        <p>Arthur (Jason Momoa) musí požádat o pomoc svého nevlastního bratra Orma (Patrick Wilson), aby ochránil Atlantidu před Black Mantou (Yahya Abdul-Mateen II), který ve své posedlé snaze pomstít smrt svého otce vypustil ničivou zbraň. (Vertical Entertainment)</p>
        <p></p>
        <h3>Hotel Palace</h3>
        <img class="News" src="./pic of movie/Hotel Palace.jpg" alt="Hotel Palace">
        <p>Komedie, Drama</p>
        <p>Itálie, Švýcarsko, Polsko, Francie, 2023, 100 min</p>
        <p>Kdysi dávno byl, a dodnes je... Hotel Palace. Neobyčejný zámek uprostřed zasněženého údolí má gotickou a pohádkovou atmosféru a scházejí se tu bohatí a požitkářští hosté z celého světa. Letos je všechny spojila jedinečná událost: silvestrovský večírek roku 2000. Jejich extravagantní požadavky se snaží plnit houf číšníků, poslíčků, kuchařů a recepčních. S blížícím se úsvitem nového tisíciletí Hansueli, obětavý padesátiletý ředitel luxusního hotelu, s téměř vojenskou přesností dohlíží na personál ještě před příchodem hostů na večírek a ujišťuje je, že to nebude konec světa. Ve vzduchu však visí Y2K a panují obavy i naděje, že úderem půlnoci může dojít k nečekaným výkyvům na účtech velkých finančníků v důsledku zhroucení světových počítačových systémů. Ve skutečnosti je však čeká bitva vedená s extravagancí a výstředností hotelových hostů. Psi a tučňáci s lidskými potřebami a lidé se zvířecími touhami. Jejich příběhy dávají život absurdní a provokativní komedii. Je konec roku 1999: nejen závěr století, ale konec celého kontroverzního tisíciletí. (Pilot Film)</p>
        <p></p>
{% endblock %}

viewer/templates/Person.html
{% extends "base.html" %}

{% block content %}
<div class="content-container">
    <h1>{{ person }}</h1>
    <div class="person-details">
        <div class="person-first-name">Jméno: {{ person.first_name }}</div>
        <div class="person-last-name">Příjmení: {{ person.last_name }}</div>
        <div class="person-birth-date">Datum narození: {{ person.birth_date }}</div>
        <div class="person-acting-in-movies">Herec:
            {% for movie in person.acting_in_movie.all %}
                <span class="person-acting-in-movie"><a href="{% url 'movie' movie.id %}">{{ movie }}</a></span>
            {% empty %}
                Nehrál v žádném filmu
            {% endfor %}
        </div>
        <div class="person-directing-movies">Režisér:
            {% for movie in person.directing_movie.all %}
                <span class="person-directing-movie"><a href="{% url 'movie' movie.id %}">{{ movie }}</a></span>
            {% empty %}
                Nerežíroval žádný film
            {% endfor %}
        </div>
        <div class="person-biography">Biografie: {{ person.biography }}</div>
        <a href="{% url 'person_update' person.id %}"><button>Upravit</button></a>
        <a href="{% url 'person_delete' person.id %}"><button>Smazat</button></a>
    </div>
</div>
{% endblock %}

viewer/templates/country_admin.html
{% extends "base.html" %}

{% block content %}
<h1>Země</h1>
<ul>
    {% for country in countries %}
    <li>
        <a href="{% url 'country' country.id %}">{{country}}</a>
        <a href="{% url 'country_update' country.id %}"><button>Upravit</button></a>
        <a href="{% url 'country_delete' country.id %}"><button>Smazat</button></a>
    </li>
    {% endfor %}
    <li>
        <a href="{% url 'create_country' %}"><button>Vytvořit nový</button></a>
    </li>
</ul>
{% endblock %}

viewer/templates/country_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post" >
    {% csrf_token %}
    <p>
        Opravdu chcete smazat záznam pro: "{{ object }}" z databáze?
    <input type="submit" value="Submit" class="btn btn-submit">
</form>
{% endblock %}

viewer/templates/country_create.html
{% extends "base.html" %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Submit" class="btn btn-submit">
</form>
{% endblock %}

viewer/templates/genre_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post" >
    {% csrf_token %}
    <p>
        Opravdu chcete smazat záznam pro: "{{ object }}" z databáze?
    <input type="submit" value="Submit" class="btn btn-submit">
</form>
{% endblock %}

viewer/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Welcome to HollyMovies</h1>
</body>
</html>

viewer/templates/movie_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post" >
    {% csrf_token %}
    <p>
        Opravdu chcete smazat záznam pro: "{{ object }}" z databáze?
    <input type="submit" value="Submit" class="btn btn-submit">
</form>
{% endblock %}

viewer/templates/movie_create.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form }}
        <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
        {{ form.media }}
    </table>
    <input type="submit" value="Submit" class="btn btn-submit">
</form>
{% endblock %}

viewer/templates/movies.html
{% extends "base.html" %}

{% block content %}
<div class="content-container">
    <h1>Žánry</h1>
    <ul>
        {% for genre in genres %}
        <li><a href="{% url 'genre' genre.id %}">{{genre}}</a>
        </li>
        {% endfor %}
    </ul>
    <h1>Seznam filmů {{ filtered_by }} </h1>
    <ul>
        {% for movie in movies %}
        <li><a href="{% url 'movie' movie.id %}">{{movie}}</a> </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

viewer/templates/movies2.html
{% extends "base.html" %}

{% block content %}
    <h1>Seznam filmů</h1>
    <ul>
        {% for movie in object_list %}
            <li><a href="{% url 'movie' movie.id %}">{{ movie }}</a></li>
        {% endfor %}
    </ul>

    <!-- pagination v1: Stránka 1 z 3 Následující -->
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Předchozí</a>
            {% endif %}
            <span>
                Stránka {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Následující</a>
            {% endif %}
        </span>
    </div>

    <!-- pagination v2: Předchozí 1 2 3 Následující -->
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Předchozí</a>
            {% endif %}
            <span>
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <span class="current-page">
                            <a href="?page={{ i }}">{{ i }}</a>
                        </span>
                    {% else %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Následující</a>
            {% endif %}
        </span>
    </div>

    <!-- pagination v3:  Předchozí 1 ... 3 4 5 6 7 ... 11 Následující  -->
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">Předchozí</a>
            {% endif %}
            <span>
                {% if page_obj.number > 3 %}
                    <a href="?page=1">1</a>
                    {% if page_obj.number > 4 %}
                        <span>...</span>
                    {% endif %}
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <span class="current-page">
                            <a href="?page={{ i }}">{{ i }}</a>
                        </span>
                    {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                        <a href="?page={{ i }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                    {% if page_obj.number < page_obj.paginator.num_pages|add:'-4' %}
                        <span>...</span>
                    {% endif %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Následující</a>
            {% endif %}
        </span>
    </div>

    {% if perms.viewer.add_movie %}
        <a href="{% url 'movie_create' %}"><button>Přidat film</button></a>
    {% endif %}
{% endblock %}

viewer/templates/movies_admin.html
{% extends "base.html" %}

{% block content %}
<h1>Filmy</h1>
<ul>
    {% for movie in movies %}
    <li>
        <a href="{% url 'movie' movie.id %}">{{movie}}</a>
        <a href="{% url 'movie_update' movie.id %}"><button>Upravit</button></a>
        <a href="{% url 'movie_delete' movie.id %}"><button>Smazat</button></a>
    </li>
    {% endfor %}
    <li>
        <a href="{% url 'movie_create' %}"><button>Vytvořit nový</button></a>
    </li>
</ul>
{% endblock %}

viewer/templates/persons2.html
{% extends "base.html" %}

{% block content %}
<h1>Seznam lidí</h1>
<ul>
    {% for person in object_list %}
        <li><a href="{% url 'person' person.id %}">{{ person }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

viewer/templates/persons_admin.html
{% extends "base.html" %}

{% block content %}
<h1>Osobnosti</h1>
<ul>
    {% for person in persons %}
    <li>
        <a href="{% url 'person' person.id %}">{{person}}</a>
        <a href="{% url 'person_update' person.id %}"><button>Upravit</button></a>
        <a href="{% url 'person_delete' person.id %}"><button>Smazat</button></a>
    </li>
    {% endfor %}
    <li>
        <a href="{% url 'person_create' %}"><button>Vytvořit nový</button></a>
    </li>
</ul>    
{% endblock %}