zkouska/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path, include
from rest_framework.templatetags import rest_framework

import api
from api.views import *
from accounts.views import *
from viewer.models import *
from viewer.views import *
from zkouska import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('hello', hello),
    path('hello2/<s>', hello2),
    path('hello3/', hello3),
    path('hello4/', hello4),

    path('', index, name='index'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),     # defaultní views pro přihlašování/odhlašován/...

    path('accounts/profile_create/<pk>', ProfileCreateView.as_view(), name='profile_create'),
    path('accounts/profile/<pk>/', profile, name='profile'),
    path('accounts/profile_edit/', profile_edit, name='profile_edit'),


    path('News/', news, name='News'),
    path('NewsOnDVD', newsOnDVD, name='NewsOnDVD'),
    path('movies/', MoviesListView.as_view(), name='movies2'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('administration/', administration, name='administration'),
    path('country_admin/', CountryView.as_view(), name='country_admin'),
    path('movies_admin/', MoviesView.as_view(), name='movies_admin'),
    # path('movies/', MoviesTemplateView.as_view(), name=MoviesTemplateView),
    # path('movies2/', MoviesListView.as_view(), name=MoviesListView),
    path('movie/<pk>/', movie, name='movie'),
    path('movie/update/<pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('actors/', actors, name='actors'),
    path('actor/<pk>/', actor, name='actor'),
    #path('person/create/', PersonCreateView.as_view(), name='person_create'),
    path('genre_admin/', GenresView.as_view(), name='genre_admin'),
    path('genre/<pk>/', movies_by_genre, name='genre'),
    path('genre/update/<pk>', GenreUpdateView.as_view(), name='genre_update'),
    path('genres/create/', GenreCreateView.as_view(), name='genre_create'),
    path('genre/delete/<pk>/', GenreDeleteView.as_view(), name='genre_delete'),
    path('country/<pk>/', movies_by_country, name='country'),
    # path('administration/', CountryView.as_view(), name='country_view'),
    path('countries/create/', CountryCreateView.as_view(), name='create_country'),
    path('countries/delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),
    path('countries/update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('persons_admin/', PersonsView.as_view(), name='persons_admin'),
    path('person/create/', PersonCreateView.as_view(), name='person_create'),
    #path('person/create/', PersonModelForm, name='person_create'),
    path('actor/update/<pk>/', PersonUpdateView.as_view(), name='person_update'),
    path('person/delete/<pk>/', PersonDeleteView.as_view(), name='person_delete'),
    path('person/<pk>/', person, name='person'),

    path('rate_movie/', rate_movie, name='rate_movie'),
    path('add_comment/', add_comment, name='add_comment'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/movies/', api.views.Movies.as_view()),

    path('api/movie/<pk>/', api.views.MovieDetail.as_view()),

    path('api/person/<pk>/', api.views.PersonDetail.as_view()),
    path('api/persons/', api.views.PersonsList.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from datetime import date, datetime

from django.db import models
from django.db.models import Model, CharField, IntegerField, TextField, DateField, ForeignKey, DO_NOTHING, \
    ManyToManyField, SET_NULL, DateTimeField, ImageField
from django.contrib.auth.models import User


# Create your models here.


class Country(Model):
    name = CharField(max_length=64, null=False, blank=False, unique=True)

    class Meta:
        verbose_name_plural = "Countries"

    def __str__(self):
        return f"{self.name}"


class Genre(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)  # CharField => VARCHAR

    def __str__(self):
        return f"{self.name}"


class Person(Model):
    first_name = CharField(max_length=32, null=False, blank=False)
    last_name = CharField(max_length=32, null=False, blank=False)
    nationality = CharField(max_length=64, null=True, blank=True)
    birth_date = DateField(null=True, blank=True)
    date_of_death = DateField(null=True, blank=True)
    biography = TextField(null=True, blank=True)
    person_image = ImageField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def calculate_age(self):
        today = datetime.now().date()

        if self.date_of_death:
            age_at_death = (self.date_of_death - self.birth_date).days // 365
            return age_at_death
        else:
            age_now = (today - self.birth_date).days // 365
            return age_now

    def get_image(self):
        return Image.objects.filter(person=self)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        ordering = ['last_name', 'first_name']


class Movie(Model):
    title_orig = CharField(max_length=64, null=False, blank=False)
    title_cz = CharField(max_length=64, null=True, blank=True)
    title_sk = CharField(max_length=64, null=True, blank=True)
    countries = ManyToManyField(Country, blank=True, related_name='movies_in_country')  # umožňuje jít oběma směry tabulek
    genres = ManyToManyField(Genre, blank=True, related_name='movies_of_genre')
    directors = ManyToManyField(Person, blank=False, related_name='directing_movie')
    actors = ManyToManyField(Person, blank=True, related_name='acting_in_movie')
    year = IntegerField(null=True, blank=True)
    video = CharField(max_length=128, null=True, blank=True)
    description = TextField(null=True, blank=True)
    movie_image = ImageField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def __str__(self):
        if self.title_cz:
            title_name = self.title_cz
        elif self.title_sk:
            title_name = self.title_sk
        else:
            title_name = self.title_orig

        if self.year is not None:
            title_name += f" ({self.year})"

        return title_name

    def get_image(self):
        return Image.objects.filter(movie=self)

    class Meta:
        ordering = ['title_orig']


class Rating(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    user = ForeignKey(User, null=True, on_delete=SET_NULL)
    rating = IntegerField(null=False, blank=False)

    def __str__(self):
        return f"{self.movie}: {self.rating} by {self.user}"


class Comment(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False)
    user = ForeignKey(User, null=True, on_delete=SET_NULL)
    comment = TextField(null=False, blank=False)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.movie}: {self.user} {self.comment[:20]}"


class Image(Model):
    movie = ForeignKey(Movie, on_delete=DO_NOTHING, null=False, blank=False, default=None)
    person_image = ForeignKey(Person, on_delete=DO_NOTHING, null=False, blank=False, default=None)
    # url = CharField(max_length=128, null=False, blank=False)
    image = ImageField(upload_to='images/', default=None, null=False, blank=False)  #, height_field=None, width_field=None, max_length=500)
    description = TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.movie}: {self.description[:50]}"

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'viewer/styless.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% if not view.is_popup %}
    <header class="headContainer">
        <img class="headContainer-part" alt="Yoda1" src="{% static 'viewer/images/HD-wallpaper-jedi-yoda-star-wars-lightsbar-black-background-dark-theme.jpg' %}">
        <a href="{% url 'index' %}"  class="headContainer-center"><h1>Endless Movie database</h1></a>
        <img class="headContainer-part" alt="Yoda2" src="{% static 'viewer/images/wp7248743.webp' %}">
    </header>
    <nav class="navContainer">
        {% if request.user.is_authenticated %}
            Přihlášen jako: {{ request.user.username }}
            <a href="{% url 'logout' %}"><button id="button-logout">Logout</button></a>
            {% if request.user.profile %}
                <a href="{% url 'profile' pk=request.user.profile.pk %}"><button id="profile-button">Profil</button></a>
            {% else %}
                <a href="{% url 'profile_create' pk=request.user.pk %}"><button id="create-profile-btn">Vyvořit profil</button></a>
            {% endif %}
        {% else %}
            <a href="{% url 'signup' %}"><button id="button-signup">Register</button></a>
            <a href="{% url 'login' %}"><button id="button-login">Login</button></a>
        {% endif %}
        {% if request.user.is_superuser %}
            <a href="/admin/"><button>Admin</button></a>
        {% endif %}
    </nav>
    <nav class="navContainer2">
        <a href="{% url 'News' %}"><button>News in Cinemas</button></a>
        <a href="{% url 'NewsOnDVD' %}"><button>News on DVD</button></a>
        <a href="{% url 'movies2' %}"><button>Movies</button></a>
        <a href="{% url 'actors' %}"><button>Actors</button></a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'movie_create' %}"><button>Create Movie</button></a>
            {% if perms.viewer.add_person  %}
                <a href="{% url 'person_create' %}"><button>Create Person</button></a>
            {% endif %}
            <a href="{% url 'administration' %}"> <button>Administrace</button></a>
        {% endif %}
        <button>Movie Shop</button>
        <button>Merchandise Store</button>
    </nav>
    <main>
        <h2>Welcome to our outstanding page about the best of Cinematography.<span id="date-time"></span></h2>
{% endif %}
        {% block content %}{% endblock %}
    </main>
    <footer>Copyright Created by Marcel Jurčák 2.12.2023</footer>
    <script src="{% static 'viewer/script.js' %}"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styless.css">
</head>
<body>
    <header class="headContainer">
        <img class="headContainer-part" alt="Yoda1" src="./pic of movie/HD-wallpaper-jedi-yoda-star-wars-lightsbar-black-background-dark-theme.jpg">
        <h1 class="headContainer-center">Endless Movie database</h1>
        <img class="headContainer-part" alt="Yoda2" src="./pic of movie/wp7248743.webp">
    </header>
    <nav class="navContainer">
        <button>Register</button>
        <button>Login</button>
    </nav>
    <nav class="navContainer2">
        <button>News in Cinemas</button>
        <button>News on DVD</button>
        <button>VOD Cinema Hub</button>
        <button>TV Recommendation</button>
        <button>Actor rankings</button>
        <button>Awards</button>
        <button>Users</button>
        <button>Movie Shop</button>
        <button>Merchandise Store</button>
    </nav>
    <main>
        <h2>Welcome to our outstanding page about the best of Cinematography.<span id="date-time"></span></h2>
        <div class="movie-box" id="movieBox">
            <div class="arrow left" onclick="showPreviousMovie()">&#9665;</div>
            <div class="movie-item" onclick="toggleVideo()">
                <div class="image-container">
                    <img class="movie-image" src="">
                </div>
            </div>
            <div class="arrow right" onclick="showNextMovie()">&#9655;</div>
            <div class="video-container">
                <video id="movieVideo" width="100%" height="100%" controls></video>
            </div>
        </div>
    </main>
    <footer>Copyrigh Created by Marcel Jurčák 2.12.2023</footer>
    <script src="script.js"></script>
</body>
</html>